class TestResources {
  getMovieListForTest() {
    return {
      data: {
        movies: [
          {
            id: "75",
            name: "Mars Attacks!",
            overview:
              "'We come in peace' is not what those green men from Mars mean when they invade our planet, armed with irresistible weapons and a cruel sense of humor.  This star studded cast must play victim to the alien’s fun and games in this comedy homage to science fiction films of the '50s and '60s.",
            similar: [
              {
                id: "314",
                name: "Catwoman",
              },
              {
                id: "364",
                name: "Batman Returns",
              },
              {
                id: "377",
                name: "A Nightmare on Elm Street",
              },
              {
                id: "395",
                name: "AVP: Alien vs. Predator",
              },
              {
                id: "11015",
                name: "The Relic",
              },
              {
                id: "11069",
                name: "Tremors 2: Aftershocks",
              },
              {
                id: "11072",
                name: "Blazing Saddles",
              },
              {
                id: "11077",
                name: "Problem Child",
              },
              {
                id: "9711",
                name: "Species III",
              },
              {
                id: "9725",
                name: "Friday the 13th Part 2",
              },
            ],
            releaseDate: "1996-12-12T00:00:00.000Z",
            crew: [
              {
                id: "52fe4214c3a36847f80022fd",
                person: {
                  name: "Larry J. Franco",
                },
                role: {
                  job: "Producer",
                },
              },
              {
                id: "52fe4214c3a36847f8002343",
                person: {
                  name: "Peter Suschitzky",
                },
                role: {
                  job: "Director of Photography",
                },
              },
              {
                id: "52fe4214c3a36847f80022eb",
                person: {
                  name: "Tim Burton",
                },
                role: {
                  job: "Director",
                },
              },
              {
                id: "52fe4214c3a36847f80022f1",
                person: {
                  name: "Tim Burton",
                },
                role: {
                  job: "Producer",
                },
              },
              {
                id: "52fe4214c3a36847f80022f7",
                person: {
                  name: "Laurie Parker",
                },
                role: {
                  job: "Producer",
                },
              },
            ],
            cast: [
              {
                id: "52fe4214c3a36847f8002301",
                person: {
                  name: "Jack Nicholson",
                  images: [
                    {
                      small: "https://image.tmdb.org/t/p/w45/6h12pZsgj3WWjMtykUgfLkLEBWz.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/gNMokbwBSrBEMiv3qDBomloe7jD.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/sX2eryfpUdlGsZOzoDlszmQYyPP.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/rmwgMiLjy1QgFCz1TDWDqpO6dq4.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/aeCqQiVzohWwwmk8VKCXOxsjobS.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/hBHcQIEa6P48HQAlLZkh0eKSSkG.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/uZyV6vZ9Ubipw89woZzY7dBaEPz.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/l0kca3XYpQktyJTwZJ6bpd9LNbF.jpg",
                    },
                  ],
                },
                role: {
                  character: "President James Dale / Art Land",
                },
              },
              {
                id: "52fe4214c3a36847f8002305",
                person: {
                  name: "Glenn Close",
                  images: [
                    {
                      small: "https://image.tmdb.org/t/p/w45/8FlKKFpUZ72oTpVKdVsjMmq1CWQ.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/bjb2dExzz0EWK4fnhfb7zs2CoEZ.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/aJm5iybGD6zj9jffsS0PoklWaa2.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/4VHZ1GfLwN7MUgApy0LCBzdDF9L.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/3Z6cFppvuzBKsR0IEWmmZU2tW24.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/eNTn3OmlnsQYLIp7HVGeH9kOJiA.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/cVxLNFLnY8HfYolhAwvz8E2CUQs.jpg",
                    },
                  ],
                },
                role: {
                  character: "First Lady Marsha Dale",
                },
              },
              {
                id: "52fe4214c3a36847f8002309",
                person: {
                  name: "Annette Bening",
                  images: [
                    {
                      small: "https://image.tmdb.org/t/p/w45/bs4hB5t2mHMn6C2ZGOlP5LfSEPe.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/vVAvoiE6FQ4couqaB0ogaHR6Ef7.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/jgG41fbSC3TK4LL67Obzrg0mTJ9.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/jxCkZrvpFV7qVmheNVd1ZEz8360.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/2PUoEjMHzx0KuvuUFPlSWkQszaw.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/kKqQgBUyZ3NL645RjE4t2vxHFr1.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/wtQ31bpNZBZeISxk6ufzZ6SLKEY.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/wufadDw4tslO94g8pXQzFtrOFCk.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/yW5vaRS00kaVXgpFDDJ4i0VyI9g.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/sBiiRwAVXd0FCRZ87m0I89qGBvy.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/an07QroJJdZIxzm70sIapS92a5j.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/27xo9WOUOzR7J9Dp3vQowz5OAsK.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/pTXTMPDMVy9qXUsQpHObIpNMosT.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/nbFeQcgzgsdNV3ZGnaBhTBwzfcY.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/hZ5gBGuXSa3qjad8ENf3ph406kV.jpg",
                    },
                  ],
                },
                role: {
                  character: "Barbara Land",
                },
              },
              {
                id: "52fe4214c3a36847f800230d",
                person: {
                  name: "Pierce Brosnan",
                  images: [
                    {
                      small: "https://image.tmdb.org/t/p/w45/dzXVwwJLPwiZeXOnf7YxorqVEEM.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/bKSi1sHf3h9kM5SG94r2WX1T8d3.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/AdFQZh4iGRT0qjwU9hTmTtyQ1xJ.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/elEQVwmIvzv4paSmNliHulor8eL.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/qjym2b0zuLTPaUyXbnwAcBKfrbG.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/nFXnm5H4Euj2pzu1uH5Pp7xnYNa.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/6AEqhFBD1OnFhaPknMnpAMi5K3L.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/jbYUIhselfijGRSR0QycIxIBjkf.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/z59cOKV7gfOPWEfQ48FLJtXNT7b.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/pJJCzXJcup0qQ30vggnPqg2q53X.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/vb3lioBAoc5CTsXrXrghYyIUtl0.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/clT3kkeXIbCBxlwarwzmz1TR0Zk.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/j0G4YtlmDrHBUmOASMNejUAkwHJ.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/dGuSvm5Gey8XtUq66mWatKs0pMC.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/4Vyrr4yoKNLe2PcKJ4gXtcdoaBU.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/uA1oCgKvKrMolgtIRwJZLp6Vb4b.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/7O0p7LjbpEUsR3t5zjmjok1vK5i.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/yXrIg6cnaI88CEyYi2mLx2Ub7fU.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/dq39bv7JHt7zjBNqxf2XE0WSCea.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/8DOXLZJROBwrG5V3e4iQuw4CaUr.jpg",
                    },
                  ],
                },
                role: {
                  character: "Professor Donald Kessler",
                },
              },
              {
                id: "52fe4214c3a36847f8002311",
                person: {
                  name: "Danny DeVito",
                  images: [
                    {
                      small: "https://image.tmdb.org/t/p/w45/uLW4Y9yjtwxtVmcJfwHZ7sKJai4.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/gNHF2SNXFFCRqwIQ2Xv6r6aV6UD.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/jKjio1yzDUfxvAnYvKlugLTmpBj.jpg",
                    },
                  ],
                },
                role: {
                  character: "Rude Gambler",
                },
              },
            ],
          },
          {
            id: "100",
            name: "Lock, Stock and Two Smoking Barrels",
            overview:
              "A card shark and his unwillingly-enlisted friends need to make a lot of cash quick after losing a sketchy poker match. To do this they decide to pull a heist on a small-time gang who happen to be operating out of the flat next door.",
            similar: [
              {
                id: "550",
                name: "Fight Club",
              },
              {
                id: "810",
                name: "Shrek the Third",
              },
              {
                id: "814",
                name: "An American Werewolf in London",
              },
              {
                id: "583",
                name: "Life of Brian",
              },
              {
                id: "855",
                name: "Black Hawk Down",
              },
              {
                id: "877",
                name: "Scarface",
              },
              {
                id: "107",
                name: "Snatch",
              },
              {
                id: "114",
                name: "Pretty Woman",
              },
              {
                id: "792",
                name: "Platoon",
              },
              {
                id: "137",
                name: "Groundhog Day",
              },
            ],
            releaseDate: "1998-08-28T00:00:00.000Z",
            crew: [
              {
                id: "52fe4217c3a36847f80035d3",
                person: {
                  name: "John Murphy",
                },
                role: {
                  job: "Original Music Composer",
                },
              },
              {
                id: "52fe4217c3a36847f8003651",
                person: {
                  name: "Guy Ritchie",
                },
                role: {
                  job: "Screenplay",
                },
              },
              {
                id: "52fe4217c3a36847f80035c1",
                person: {
                  name: "Guy Ritchie",
                },
                role: {
                  job: "Director",
                },
              },
              {
                id: "52fe4217c3a36847f80035f1",
                person: {
                  name: "Guy Ritchie",
                },
                role: {
                  job: "Casting",
                },
              },
              {
                id: "52fe4217c3a36847f80035c7",
                person: {
                  name: "Matthew Vaughn",
                },
                role: {
                  job: "Producer",
                },
              },
            ],
            cast: [
              {
                id: "52fe4217c3a36847f80035fb",
                person: {
                  name: "Jason Flemyng",
                  images: [
                    {
                      small: "https://image.tmdb.org/t/p/w45/6E5KfjDwm00jIfN3LNLL9jZAvx3.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/4jL6MmeqL1Bj9WbxIR4QxNDNKJR.jpg",
                    },
                  ],
                },
                role: {
                  character: "Tom",
                },
              },
              {
                id: "52fe4217c3a36847f80035ff",
                person: {
                  name: "Dexter Fletcher",
                  images: [
                    {
                      small: "https://image.tmdb.org/t/p/w45/yRI8MDB5sg8b8EZkzFz5cCBrnKL.jpg",
                    },
                  ],
                },
                role: {
                  character: "Soap",
                },
              },
              {
                id: "52fe4217c3a36847f8003603",
                person: {
                  name: "Nick Moran",
                  images: [
                    {
                      small: "https://image.tmdb.org/t/p/w45/kfWebCAm72JBZLXcNbA2Myr950E.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/axkvneEJuPDAwIyoCBSCZIG9pOz.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/dbnNL3Nn8K3wRJkfd26o9vU5ZJM.jpg",
                    },
                  ],
                },
                role: {
                  character: "Eddie",
                },
              },
              {
                id: "52fe4217c3a36847f8003607",
                person: {
                  name: "Jason Statham",
                  images: [
                    {
                      small: "https://image.tmdb.org/t/p/w45/lldeQ91GwIVff43JBrpdbAAeYWj.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/whNwkEQYWLFJA8ij0WyOOAD5xhQ.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/qrRIGfZ4ikHMMIRbBQAXjPkGPst.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/dyTg1DxmBmTahRw4g0ImwseXS5H.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/dqsoVOHWyK4YfxdY0odIyZxhuDB.jpg",
                    },
                  ],
                },
                role: {
                  character: "Bacon",
                },
              },
              {
                id: "52fe4217c3a36847f800360f",
                person: {
                  name: "Vinnie Jones",
                  images: [
                    {
                      small: "https://image.tmdb.org/t/p/w45/tkYWG9gY2QpoBfOh4OWNz8yQfsw.jpg",
                    },
                    {
                      small: "https://image.tmdb.org/t/p/w45/qPoNkKWGYl9EosP4l63tS8Yp7tV.jpg",
                    },
                  ],
                },
                role: {
                  character: "Big Chris",
                },
              },
            ],
          },
        ],
      },
      extensions: {
        tracing: {
          version: 1,
          startTime: "2022-01-09T12:22:08.627Z",
          endTime: "2022-01-09T12:22:09.780Z",
          duration: 1152629949,
          execution: {
            resolvers: [
              {
                path: ["movies"],
                parentType: "Query",
                fieldName: "movies",
                returnType: "[Movie!]!",
                startOffset: 172924599,
                duration: 320602622,
              },
              {
                path: ["movies", 0, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 493710102,
                duration: 109917,
              },
              {
                path: ["movies", 0, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 493895805,
                duration: 18694,
              },
              {
                path: ["movies", 0, "overview"],
                parentType: "Movie",
                fieldName: "overview",
                returnType: "String!",
                startOffset: 493935740,
                duration: 19487,
              },
              {
                path: ["movies", 0, "similar"],
                parentType: "Movie",
                fieldName: "similar",
                returnType: "[Movie!]!",
                startOffset: 493996563,
                duration: 614277186,
              },
              {
                path: ["movies", 0, "releaseDate"],
                parentType: "Movie",
                fieldName: "releaseDate",
                returnType: "DateTime",
                startOffset: 494516826,
                duration: 39005,
              },
              {
                path: ["movies", 0, "crew"],
                parentType: "Movie",
                fieldName: "crew",
                returnType: "[Credit!]!",
                startOffset: 497197022,
                duration: 3328015,
              },
              {
                path: ["movies", 0, "cast"],
                parentType: "Movie",
                fieldName: "cast",
                returnType: "[Credit!]!",
                startOffset: 498390665,
                duration: 3115289,
              },
              {
                path: ["movies", 1, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 498999974,
                duration: 24158,
              },
              {
                path: ["movies", 1, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 499054423,
                duration: 12469,
              },
              {
                path: ["movies", 1, "overview"],
                parentType: "Movie",
                fieldName: "overview",
                returnType: "String!",
                startOffset: 499087711,
                duration: 10886,
              },
              {
                path: ["movies", 1, "similar"],
                parentType: "Movie",
                fieldName: "similar",
                returnType: "[Movie!]!",
                startOffset: 499123632,
                duration: 652745329,
              },
              {
                path: ["movies", 1, "releaseDate"],
                parentType: "Movie",
                fieldName: "releaseDate",
                returnType: "DateTime",
                startOffset: 499240251,
                duration: 13433,
              },
              {
                path: ["movies", 1, "crew"],
                parentType: "Movie",
                fieldName: "crew",
                returnType: "[Credit!]!",
                startOffset: 499476176,
                duration: 2775362,
              },
              {
                path: ["movies", 1, "cast"],
                parentType: "Movie",
                fieldName: "cast",
                returnType: "[Credit!]!",
                startOffset: 499848598,
                duration: 2921480,
              },
              {
                path: ["movies", 0, "crew", 0, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 500581478,
                duration: 20033,
              },
              {
                path: ["movies", 0, "crew", 0, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 500619562,
                duration: 195594573,
              },
              {
                path: ["movies", 0, "crew", 0, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 500924645,
                duration: 3189991,
              },
              {
                path: ["movies", 0, "crew", 1, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 501044412,
                duration: 15137,
              },
              {
                path: ["movies", 0, "crew", 1, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 501078799,
                duration: 191929294,
              },
              {
                path: ["movies", 0, "crew", 1, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 501159709,
                duration: 5601325,
              },
              {
                path: ["movies", 0, "crew", 2, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 501193388,
                duration: 12118,
              },
              {
                path: ["movies", 0, "crew", 2, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 501218225,
                duration: 293410630,
              },
              {
                path: ["movies", 0, "crew", 2, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 501276878,
                duration: 5552824,
              },
              {
                path: ["movies", 0, "crew", 3, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 501304570,
                duration: 10233,
              },
              {
                path: ["movies", 0, "crew", 3, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 501329321,
                duration: 293406015,
              },
              {
                path: ["movies", 0, "crew", 3, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 501387056,
                duration: 5503407,
              },
              {
                path: ["movies", 0, "crew", 4, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 501414864,
                duration: 10995,
              },
              {
                path: ["movies", 0, "crew", 4, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 501437671,
                duration: 190412669,
              },
              {
                path: ["movies", 0, "crew", 4, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 501490017,
                duration: 5460079,
              },
              {
                path: ["movies", 0, "cast", 0, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 501535520,
                duration: 9061,
              },
              {
                path: ["movies", 0, "cast", 0, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 501555640,
                duration: 352249118,
              },
              {
                path: ["movies", 0, "cast", 0, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 501610212,
                duration: 5404695,
              },
              {
                path: ["movies", 0, "cast", 1, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 501636039,
                duration: 9667,
              },
              {
                path: ["movies", 0, "cast", 1, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 501657768,
                duration: 365332584,
              },
              {
                path: ["movies", 0, "cast", 1, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 501722985,
                duration: 5365714,
              },
              {
                path: ["movies", 0, "cast", 2, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 501748169,
                duration: 8317,
              },
              {
                path: ["movies", 0, "cast", 2, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 501767292,
                duration: 196059446,
              },
              {
                path: ["movies", 0, "cast", 2, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 501845366,
                duration: 5299459,
              },
              {
                path: ["movies", 0, "cast", 3, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 501871877,
                duration: 8517,
              },
              {
                path: ["movies", 0, "cast", 3, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 501891757,
                duration: 476342236,
              },
              {
                path: ["movies", 0, "cast", 3, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 501945664,
                duration: 5259044,
              },
              {
                path: ["movies", 0, "cast", 4, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 501978316,
                duration: 8439,
              },
              {
                path: ["movies", 0, "cast", 4, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 501998787,
                duration: 549758240,
              },
              {
                path: ["movies", 0, "cast", 4, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 502053321,
                duration: 5212050,
              },
              {
                path: ["movies", 1, "crew", 0, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 502279883,
                duration: 11745,
              },
              {
                path: ["movies", 1, "crew", 0, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 502303776,
                duration: 187787456,
              },
              {
                path: ["movies", 1, "crew", 0, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 502361496,
                duration: 5835557,
              },
              {
                path: ["movies", 1, "crew", 1, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 502410187,
                duration: 9927,
              },
              {
                path: ["movies", 1, "crew", 1, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 502438077,
                duration: 489460767,
              },
              {
                path: ["movies", 1, "crew", 1, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 502487836,
                duration: 5807081,
              },
              {
                path: ["movies", 1, "crew", 2, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 502512527,
                duration: 8929,
              },
              {
                path: ["movies", 1, "crew", 2, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 502531899,
                duration: 489449092,
              },
              {
                path: ["movies", 1, "crew", 2, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 502572666,
                duration: 5780556,
              },
              {
                path: ["movies", 1, "crew", 3, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 502596582,
                duration: 8628,
              },
              {
                path: ["movies", 1, "crew", 3, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 502615419,
                duration: 489397175,
              },
              {
                path: ["movies", 1, "crew", 3, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 502654620,
                duration: 5822899,
              },
              {
                path: ["movies", 1, "crew", 4, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 502678047,
                duration: 9037,
              },
              {
                path: ["movies", 1, "crew", 4, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 502697469,
                duration: 191392014,
              },
              {
                path: ["movies", 1, "crew", 4, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 502754374,
                duration: 5782517,
              },
              {
                path: ["movies", 1, "cast", 0, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 502788515,
                duration: 10219,
              },
              {
                path: ["movies", 1, "cast", 0, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 502811337,
                duration: 584976830,
              },
              {
                path: ["movies", 1, "cast", 0, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 502852025,
                duration: 5740189,
              },
              {
                path: ["movies", 1, "cast", 1, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 502876235,
                duration: 8104,
              },
              {
                path: ["movies", 1, "cast", 1, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 502894511,
                duration: 566009753,
              },
              {
                path: ["movies", 1, "cast", 1, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 502932840,
                duration: 5716308,
              },
              {
                path: ["movies", 1, "cast", 2, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 502955379,
                duration: 7789,
              },
              {
                path: ["movies", 1, "cast", 2, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 502973437,
                duration: 551316195,
              },
              {
                path: ["movies", 1, "cast", 2, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 503011616,
                duration: 5691216,
              },
              {
                path: ["movies", 1, "cast", 3, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 503034980,
                duration: 7940,
              },
              {
                path: ["movies", 1, "cast", 3, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 503053071,
                duration: 270701111,
              },
              {
                path: ["movies", 1, "cast", 3, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 503092183,
                duration: 5664549,
              },
              {
                path: ["movies", 1, "cast", 4, "id"],
                parentType: "Credit",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 503115510,
                duration: 7853,
              },
              {
                path: ["movies", 1, "cast", 4, "person"],
                parentType: "Credit",
                fieldName: "person",
                returnType: "Person",
                startOffset: 503134658,
                duration: 608991631,
              },
              {
                path: ["movies", 1, "cast", 4, "role"],
                parentType: "Credit",
                fieldName: "role",
                returnType: "CreditType!",
                startOffset: 503173500,
                duration: 5639992,
              },
              {
                path: ["movies", 0, "crew", 0, "role", "job"],
                parentType: "Crew",
                fieldName: "job",
                returnType: "String!",
                startOffset: 506668671,
                duration: 25086,
              },
              {
                path: ["movies", 0, "crew", 1, "role", "job"],
                parentType: "Crew",
                fieldName: "job",
                returnType: "String!",
                startOffset: 506789973,
                duration: 11252,
              },
              {
                path: ["movies", 0, "crew", 2, "role", "job"],
                parentType: "Crew",
                fieldName: "job",
                returnType: "String!",
                startOffset: 506853363,
                duration: 10241,
              },
              {
                path: ["movies", 0, "crew", 3, "role", "job"],
                parentType: "Crew",
                fieldName: "job",
                returnType: "String!",
                startOffset: 506913614,
                duration: 10371,
              },
              {
                path: ["movies", 0, "crew", 4, "role", "job"],
                parentType: "Crew",
                fieldName: "job",
                returnType: "String!",
                startOffset: 506973059,
                duration: 16093,
              },
              {
                path: ["movies", 0, "cast", 0, "role", "character"],
                parentType: "Cast",
                fieldName: "character",
                returnType: "String!",
                startOffset: 507049029,
                duration: 13222,
              },
              {
                path: ["movies", 0, "cast", 1, "role", "character"],
                parentType: "Cast",
                fieldName: "character",
                returnType: "String!",
                startOffset: 507110301,
                duration: 9565,
              },
              {
                path: ["movies", 0, "cast", 2, "role", "character"],
                parentType: "Cast",
                fieldName: "character",
                returnType: "String!",
                startOffset: 507168120,
                duration: 9877,
              },
              {
                path: ["movies", 0, "cast", 3, "role", "character"],
                parentType: "Cast",
                fieldName: "character",
                returnType: "String!",
                startOffset: 507225424,
                duration: 9542,
              },
              {
                path: ["movies", 0, "cast", 4, "role", "character"],
                parentType: "Cast",
                fieldName: "character",
                returnType: "String!",
                startOffset: 507286470,
                duration: 9617,
              },
              {
                path: ["movies", 1, "crew", 0, "role", "job"],
                parentType: "Crew",
                fieldName: "job",
                returnType: "String!",
                startOffset: 508247528,
                duration: 18503,
              },
              {
                path: ["movies", 1, "crew", 1, "role", "job"],
                parentType: "Crew",
                fieldName: "job",
                returnType: "String!",
                startOffset: 508319251,
                duration: 10447,
              },
              {
                path: ["movies", 1, "crew", 2, "role", "job"],
                parentType: "Crew",
                fieldName: "job",
                returnType: "String!",
                startOffset: 508434226,
                duration: 11555,
              },
              {
                path: ["movies", 1, "crew", 3, "role", "job"],
                parentType: "Crew",
                fieldName: "job",
                returnType: "String!",
                startOffset: 508500320,
                duration: 10028,
              },
              {
                path: ["movies", 1, "crew", 4, "role", "job"],
                parentType: "Crew",
                fieldName: "job",
                returnType: "String!",
                startOffset: 508558270,
                duration: 9496,
              },
              {
                path: ["movies", 1, "cast", 0, "role", "character"],
                parentType: "Cast",
                fieldName: "character",
                returnType: "String!",
                startOffset: 508614544,
                duration: 9809,
              },
              {
                path: ["movies", 1, "cast", 1, "role", "character"],
                parentType: "Cast",
                fieldName: "character",
                returnType: "String!",
                startOffset: 508669921,
                duration: 8713,
              },
              {
                path: ["movies", 1, "cast", 2, "role", "character"],
                parentType: "Cast",
                fieldName: "character",
                returnType: "String!",
                startOffset: 508722751,
                duration: 8981,
              },
              {
                path: ["movies", 1, "cast", 3, "role", "character"],
                parentType: "Cast",
                fieldName: "character",
                returnType: "String!",
                startOffset: 508776994,
                duration: 8844,
              },
              {
                path: ["movies", 1, "cast", 4, "role", "character"],
                parentType: "Cast",
                fieldName: "character",
                returnType: "String!",
                startOffset: 508833921,
                duration: 8782,
              },
              {
                path: ["movies", 1, "crew", 0, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 690174715,
                duration: 36431,
              },
              {
                path: ["movies", 0, "crew", 4, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 691910338,
                duration: 25521,
              },
              {
                path: ["movies", 0, "crew", 1, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 693051092,
                duration: 17975,
              },
              {
                path: ["movies", 1, "crew", 4, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 694129464,
                duration: 17883,
              },
              {
                path: ["movies", 0, "crew", 0, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 696254021,
                duration: 17178,
              },
              {
                path: ["movies", 0, "cast", 2, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 697874822,
                duration: 16028,
              },
              {
                path: ["movies", 0, "cast", 2, "person", "images"],
                parentType: "Person",
                fieldName: "images",
                returnType: "[Photo!]!",
                startOffset: 697910972,
                duration: 23904,
              },
              {
                path: ["movies", 0, "cast", 2, "person", "images", 0, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 697967897,
                duration: 156679,
              },
              {
                path: ["movies", 0, "cast", 2, "person", "images", 1, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 712608157,
                duration: 43693,
              },
              {
                path: ["movies", 0, "cast", 2, "person", "images", 2, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 712982411,
                duration: 17241,
              },
              {
                path: ["movies", 0, "cast", 2, "person", "images", 3, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 713224948,
                duration: 15293,
              },
              {
                path: ["movies", 0, "cast", 2, "person", "images", 4, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 713497494,
                duration: 16926,
              },
              {
                path: ["movies", 0, "cast", 2, "person", "images", 5, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 714540778,
                duration: 27528,
              },
              {
                path: ["movies", 0, "cast", 2, "person", "images", 6, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 714806572,
                duration: 15876,
              },
              {
                path: ["movies", 0, "cast", 2, "person", "images", 7, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 715035222,
                duration: 14781,
              },
              {
                path: ["movies", 0, "cast", 2, "person", "images", 8, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 715267921,
                duration: 15938,
              },
              {
                path: ["movies", 0, "cast", 2, "person", "images", 9, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 715924412,
                duration: 24636,
              },
              {
                path: ["movies", 0, "cast", 2, "person", "images", 10, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 716199933,
                duration: 16585,
              },
              {
                path: ["movies", 0, "cast", 2, "person", "images", 11, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 716440738,
                duration: 15275,
              },
              {
                path: ["movies", 0, "cast", 2, "person", "images", 12, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 716663256,
                duration: 14417,
              },
              {
                path: ["movies", 0, "cast", 2, "person", "images", 13, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 716883808,
                duration: 14121,
              },
              {
                path: ["movies", 0, "cast", 2, "person", "images", 14, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 717181026,
                duration: 19670,
              },
              {
                path: ["movies", 1, "cast", 3, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 773827483,
                duration: 33811,
              },
              {
                path: ["movies", 1, "cast", 3, "person", "images"],
                parentType: "Person",
                fieldName: "images",
                returnType: "[Photo!]!",
                startOffset: 773882989,
                duration: 16584,
              },
              {
                path: ["movies", 1, "cast", 3, "person", "images", 0, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 773924120,
                duration: 29715,
              },
              {
                path: ["movies", 1, "cast", 3, "person", "images", 1, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 774309472,
                duration: 20487,
              },
              {
                path: ["movies", 1, "cast", 3, "person", "images", 2, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 774661937,
                duration: 20747,
              },
              {
                path: ["movies", 1, "cast", 3, "person", "images", 3, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 774882347,
                duration: 15904,
              },
              {
                path: ["movies", 1, "cast", 3, "person", "images", 4, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 775088518,
                duration: 12816,
              },
              {
                path: ["movies", 0, "crew", 2, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 794695394,
                duration: 30205,
              },
              {
                path: ["movies", 0, "crew", 3, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 794761522,
                duration: 8577,
              },
              {
                path: ["movies", 0, "cast", 0, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 853890280,
                duration: 31357,
              },
              {
                path: ["movies", 0, "cast", 0, "person", "images"],
                parentType: "Person",
                fieldName: "images",
                returnType: "[Photo!]!",
                startOffset: 853944559,
                duration: 16399,
              },
              {
                path: ["movies", 0, "cast", 0, "person", "images", 0, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 853987250,
                duration: 18456,
              },
              {
                path: ["movies", 0, "cast", 0, "person", "images", 1, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 854347007,
                duration: 41494,
              },
              {
                path: ["movies", 0, "cast", 0, "person", "images", 2, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 854623429,
                duration: 16048,
              },
              {
                path: ["movies", 0, "cast", 0, "person", "images", 3, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 854841139,
                duration: 17770,
              },
              {
                path: ["movies", 0, "cast", 0, "person", "images", 4, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 855048600,
                duration: 13723,
              },
              {
                path: ["movies", 0, "cast", 0, "person", "images", 5, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 855256479,
                duration: 10563,
              },
              {
                path: ["movies", 0, "cast", 0, "person", "images", 6, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 855446074,
                duration: 12006,
              },
              {
                path: ["movies", 0, "cast", 0, "person", "images", 7, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 855656230,
                duration: 11762,
              },
              {
                path: ["movies", 0, "cast", 1, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 867075852,
                duration: 32746,
              },
              {
                path: ["movies", 0, "cast", 1, "person", "images"],
                parentType: "Person",
                fieldName: "images",
                returnType: "[Photo!]!",
                startOffset: 867131388,
                duration: 17008,
              },
              {
                path: ["movies", 0, "cast", 1, "person", "images", 0, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 867178372,
                duration: 13563,
              },
              {
                path: ["movies", 0, "cast", 1, "person", "images", 1, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 867575993,
                duration: 15414,
              },
              {
                path: ["movies", 0, "cast", 1, "person", "images", 2, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 867797399,
                duration: 11607,
              },
              {
                path: ["movies", 0, "cast", 1, "person", "images", 3, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 867992180,
                duration: 10366,
              },
              {
                path: ["movies", 0, "cast", 1, "person", "images", 4, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 868180662,
                duration: 10339,
              },
              {
                path: ["movies", 0, "cast", 1, "person", "images", 5, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 868371613,
                duration: 10040,
              },
              {
                path: ["movies", 0, "cast", 1, "person", "images", 6, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 868557790,
                duration: 9954,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 978355199,
                duration: 8120421,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images"],
                parentType: "Person",
                fieldName: "images",
                returnType: "[Photo!]!",
                startOffset: 986544879,
                duration: 22258,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 0, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 986612339,
                duration: 15993,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 1, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 987050539,
                duration: 16709,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 2, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 987278406,
                duration: 11000,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 3, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 987493884,
                duration: 12405,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 4, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 987699837,
                duration: 10536,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 5, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 987890446,
                duration: 10301,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 6, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 988087088,
                duration: 10090,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 7, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 988281049,
                duration: 10362,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 8, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 988470976,
                duration: 10388,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 9, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 988661382,
                duration: 10418,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 10, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 988868913,
                duration: 11423,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 11, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 989063279,
                duration: 10283,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 12, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 989254095,
                duration: 10262,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 13, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 989438837,
                duration: 10089,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 14, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 989621749,
                duration: 14767,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 15, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 989823292,
                duration: 10489,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 16, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 990020655,
                duration: 10129,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 17, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 990209433,
                duration: 10072,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 18, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 990477612,
                duration: 15468,
              },
              {
                path: ["movies", 0, "cast", 3, "person", "images", 19, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 990695082,
                duration: 10361,
              },
              {
                path: ["movies", 1, "crew", 1, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 991949161,
                duration: 22593,
              },
              {
                path: ["movies", 1, "crew", 2, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 991998772,
                duration: 8416,
              },
              {
                path: ["movies", 1, "crew", 3, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 992027513,
                duration: 7244,
              },
              {
                path: ["movies", 0, "cast", 4, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1051828456,
                duration: 29877,
              },
              {
                path: ["movies", 0, "cast", 4, "person", "images"],
                parentType: "Person",
                fieldName: "images",
                returnType: "[Photo!]!",
                startOffset: 1051882014,
                duration: 21998,
              },
              {
                path: ["movies", 0, "cast", 4, "person", "images", 0, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 1051930424,
                duration: 13078,
              },
              {
                path: ["movies", 0, "cast", 4, "person", "images", 1, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 1052407434,
                duration: 17355,
              },
              {
                path: ["movies", 0, "cast", 4, "person", "images", 2, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 1052696318,
                duration: 15940,
              },
              {
                path: ["movies", 1, "cast", 2, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1054391121,
                duration: 20873,
              },
              {
                path: ["movies", 1, "cast", 2, "person", "images"],
                parentType: "Person",
                fieldName: "images",
                returnType: "[Photo!]!",
                startOffset: 1054433028,
                duration: 14408,
              },
              {
                path: ["movies", 1, "cast", 2, "person", "images", 0, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 1054470748,
                duration: 9912,
              },
              {
                path: ["movies", 1, "cast", 2, "person", "images", 1, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 1054752511,
                duration: 11322,
              },
              {
                path: ["movies", 1, "cast", 2, "person", "images", 2, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 1054954382,
                duration: 10896,
              },
              {
                path: ["movies", 1, "cast", 1, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1068981764,
                duration: 29840,
              },
              {
                path: ["movies", 1, "cast", 1, "person", "images"],
                parentType: "Person",
                fieldName: "images",
                returnType: "[Photo!]!",
                startOffset: 1069034887,
                duration: 16038,
              },
              {
                path: ["movies", 1, "cast", 1, "person", "images", 0, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 1069077035,
                duration: 11831,
              },
              {
                path: ["movies", 1, "cast", 0, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1087869581,
                duration: 30487,
              },
              {
                path: ["movies", 1, "cast", 0, "person", "images"],
                parentType: "Person",
                fieldName: "images",
                returnType: "[Photo!]!",
                startOffset: 1087924534,
                duration: 22793,
              },
              {
                path: ["movies", 1, "cast", 0, "person", "images", 0, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 1087972328,
                duration: 12415,
              },
              {
                path: ["movies", 1, "cast", 0, "person", "images", 1, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 1088331517,
                duration: 13435,
              },
              {
                path: ["movies", 0, "similar", 0, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1108382189,
                duration: 30065,
              },
              {
                path: ["movies", 0, "similar", 0, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1108433251,
                duration: 9369,
              },
              {
                path: ["movies", 0, "similar", 1, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1108469076,
                duration: 8304,
              },
              {
                path: ["movies", 0, "similar", 1, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1108490258,
                duration: 7173,
              },
              {
                path: ["movies", 0, "similar", 2, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1108515470,
                duration: 7537,
              },
              {
                path: ["movies", 0, "similar", 2, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1108534756,
                duration: 6574,
              },
              {
                path: ["movies", 0, "similar", 3, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1108559428,
                duration: 7375,
              },
              {
                path: ["movies", 0, "similar", 3, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1108578377,
                duration: 6530,
              },
              {
                path: ["movies", 0, "similar", 4, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1108602192,
                duration: 7214,
              },
              {
                path: ["movies", 0, "similar", 4, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1108621133,
                duration: 6483,
              },
              {
                path: ["movies", 0, "similar", 5, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1108644555,
                duration: 7051,
              },
              {
                path: ["movies", 0, "similar", 5, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1108662812,
                duration: 6498,
              },
              {
                path: ["movies", 0, "similar", 6, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1108685797,
                duration: 6958,
              },
              {
                path: ["movies", 0, "similar", 6, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1108703832,
                duration: 6432,
              },
              {
                path: ["movies", 0, "similar", 7, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1108726918,
                duration: 7124,
              },
              {
                path: ["movies", 0, "similar", 7, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1108745439,
                duration: 6377,
              },
              {
                path: ["movies", 0, "similar", 8, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1108767885,
                duration: 7065,
              },
              {
                path: ["movies", 0, "similar", 8, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1108786309,
                duration: 6496,
              },
              {
                path: ["movies", 0, "similar", 9, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1108810072,
                duration: 7230,
              },
              {
                path: ["movies", 0, "similar", 9, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1108828453,
                duration: 6368,
              },
              {
                path: ["movies", 1, "cast", 4, "person", "name"],
                parentType: "Person",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1112197357,
                duration: 29551,
              },
              {
                path: ["movies", 1, "cast", 4, "person", "images"],
                parentType: "Person",
                fieldName: "images",
                returnType: "[Photo!]!",
                startOffset: 1112249468,
                duration: 15448,
              },
              {
                path: ["movies", 1, "cast", 4, "person", "images", 0, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 1112290201,
                duration: 11698,
              },
              {
                path: ["movies", 1, "cast", 4, "person", "images", 1, "small"],
                parentType: "Photo",
                fieldName: "small",
                returnType: "URL",
                startOffset: 1112678487,
                duration: 15152,
              },
              {
                path: ["movies", 1, "similar", 0, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1151944726,
                duration: 31521,
              },
              {
                path: ["movies", 1, "similar", 0, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1151995763,
                duration: 9388,
              },
              {
                path: ["movies", 1, "similar", 1, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1152037506,
                duration: 8724,
              },
              {
                path: ["movies", 1, "similar", 1, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1152059848,
                duration: 7416,
              },
              {
                path: ["movies", 1, "similar", 2, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1152087148,
                duration: 8690,
              },
              {
                path: ["movies", 1, "similar", 2, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1152107859,
                duration: 11876,
              },
              {
                path: ["movies", 1, "similar", 3, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1152138177,
                duration: 7842,
              },
              {
                path: ["movies", 1, "similar", 3, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1152157513,
                duration: 6629,
              },
              {
                path: ["movies", 1, "similar", 4, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1152181373,
                duration: 7533,
              },
              {
                path: ["movies", 1, "similar", 4, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1152200774,
                duration: 6590,
              },
              {
                path: ["movies", 1, "similar", 5, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1152223774,
                duration: 7266,
              },
              {
                path: ["movies", 1, "similar", 5, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1152243957,
                duration: 6547,
              },
              {
                path: ["movies", 1, "similar", 6, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1152266566,
                duration: 7310,
              },
              {
                path: ["movies", 1, "similar", 6, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1152284712,
                duration: 6665,
              },
              {
                path: ["movies", 1, "similar", 7, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1152307459,
                duration: 7372,
              },
              {
                path: ["movies", 1, "similar", 7, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1152326320,
                duration: 6672,
              },
              {
                path: ["movies", 1, "similar", 8, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1152350274,
                duration: 7960,
              },
              {
                path: ["movies", 1, "similar", 8, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1152370428,
                duration: 6676,
              },
              {
                path: ["movies", 1, "similar", 9, "id"],
                parentType: "Movie",
                fieldName: "id",
                returnType: "ID!",
                startOffset: 1152393137,
                duration: 7360,
              },
              {
                path: ["movies", 1, "similar", 9, "name"],
                parentType: "Movie",
                fieldName: "name",
                returnType: "String!",
                startOffset: 1152411842,
                duration: 6731,
              },
            ],
          },
        },
        cacheControl: {
          version: 1,
          hints: [
            {
              path: ["movies"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "similar"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "crew"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "cast"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "similar"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "crew"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "cast"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "crew", 0, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "crew", 1, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "crew", 2, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "crew", 3, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "crew", 4, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "cast", 0, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "cast", 1, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "cast", 2, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "cast", 3, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "cast", 4, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "crew", 0, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "crew", 1, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "crew", 2, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "crew", 3, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "crew", 4, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "cast", 0, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "cast", 1, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "cast", 2, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "cast", 3, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "cast", 4, "person"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "cast", 2, "person", "images"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "cast", 3, "person", "images"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "cast", 0, "person", "images"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "cast", 1, "person", "images"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "cast", 3, "person", "images"],
              maxAge: 0,
            },
            {
              path: ["movies", 0, "cast", 4, "person", "images"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "cast", 2, "person", "images"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "cast", 1, "person", "images"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "cast", 0, "person", "images"],
              maxAge: 0,
            },
            {
              path: ["movies", 1, "cast", 4, "person", "images"],
              maxAge: 0,
            },
          ],
        },
      },
    };
  }
  getWikipediaTestArray() {
    return [
      {
        ns: 0,
        title: "Fight Club",
        pageid: 1009041,
        size: 97608,
        wordcount: 10491,
        snippet:
          '<span class="searchmatch">Fight</span> <span class="searchmatch">Club</span> is a 1999 American film directed by David Fincher and starring Brad Pitt, Edward Norton, and Helena Bonham Carter. It is based on the 1996 novel',
        timestamp: "2021-12-29T00:28:21Z",
      },

      {
        ns: 0,
        title: "Fight Club (novel)",
        pageid: 23854860,
        size: 43850,
        wordcount: 5541,
        snippet:
          '<span class="searchmatch">Fight</span> <span class="searchmatch">Club</span> is a 1996 novel by Chuck Palahniuk. It follows the experiences of an unnamed protagonist struggling with insomnia. Inspired by his doctor\'s',
        timestamp: "2022-01-07T03:23:21Z",
      },
      {
        ns: 0,
        title: "The Narrator (Fight Club)",
        pageid: 51255835,
        size: 13137,
        wordcount: 1420,
        snippet:
          '1996 Chuck Palahniuk novel <span class="searchmatch">Fight</span> <span class="searchmatch">Club</span>, its 1999 film adaptation of the same name, and the comic books <span class="searchmatch">Fight</span> <span class="searchmatch">Club</span> 2 and <span class="searchmatch">Fight</span> <span class="searchmatch">Club</span> 3. The character is an insomniac',
        timestamp: "2021-11-22T02:05:44Z",
      },
      {
        ns: 0,
        title: "Fight Club 3",
        pageid: 61206061,
        size: 2136,
        wordcount: 82,
        snippet:
          '<span class="searchmatch">Fight</span> <span class="searchmatch">Club</span> 3 is Chuck Palahniuk\'s second comic book meta-sequel to his 1996 novel <span class="searchmatch">Fight</span> <span class="searchmatch">Club</span>. <span class="searchmatch">Fight</span> <span class="searchmatch">Club</span> 3 consists of twelve issues, with the first issue',
        timestamp: "2021-05-28T05:35:06Z",
      },
      {
        ns: 0,
        title: "Fight Club 2",
        pageid: 45657955,
        size: 19129,
        wordcount: 650,
        snippet:
          '<span class="searchmatch">Fight</span> <span class="searchmatch">Club</span> 2 (also known as <span class="searchmatch">Fight</span> <span class="searchmatch">Club</span> 2: The Tranquility Gambit) is Chuck Palahniuk\'s comic book meta-sequel to his 1996 novel <span class="searchmatch">Fight</span> <span class="searchmatch">Club</span>, with art by',
        timestamp: "2021-11-03T04:54:59Z",
      },
      {
        ns: 0,
        title: "Interpretations of Fight Club",
        pageid: 22827640,
        size: 22509,
        wordcount: 2973,
        snippet:
          'The 1999 American film <span class="searchmatch">Fight</span> <span class="searchmatch">Club</span>, directed by David Fincher, presents social commentary about consumerist culture, especially the feminization of American',
        timestamp: "2021-11-07T16:34:31Z",
      },
      {
        ns: 0,
        title: "Fight Club (disambiguation)",
        pageid: 2313757,
        size: 1107,
        wordcount: 175,
        snippet:
          '<span class="searchmatch">Fight</span> <span class="searchmatch">Club</span> is a 1999 film directed by David Fincher. <span class="searchmatch">Fight</span> <span class="searchmatch">Club</span> may also refer to: <span class="searchmatch">Fight</span> <span class="searchmatch">Club</span> (novel), a 1996 novel by Chuck Palahniuk on which Fincher\'s',
        timestamp: "2021-10-09T22:26:57Z",
      },
      {
        ns: 0,
        title: "Jurassic Fight Club",
        pageid: 18320302,
        size: 8979,
        wordcount: 266,
        snippet:
          'Jurassic <span class="searchmatch">Fight</span> <span class="searchmatch">Club</span> (titled Dinosaur Secrets in Australia/the UK) is a paleontology-based television series on History channel which premiered in the US',
        timestamp: "2021-12-26T02:28:28Z",
      },
      {
        ns: 0,
        title: "Fight Club – Members Only",
        pageid: 9114950,
        size: 9976,
        wordcount: 997,
        snippet:
          '<span class="searchmatch">Fight</span> <span class="searchmatch">Club</span>: Members Only is a 2006 Indian action film directed by Vikram Chopra and produced by Ravi Walia and Sohail Khan. The film features an ensemble',
        timestamp: "2021-12-31T04:59:18Z",
      },
      {
        ns: 0,
        title: "The Fight Club",
        pageid: 25343936,
        size: 15706,
        wordcount: 2077,
        snippet:
          'The <span class="searchmatch">Fight</span> <span class="searchmatch">Club</span> is a Canadian mixed martial arts (MMA) promotion based in Edmonton, Alberta. TFC currently <span class="searchmatch">fights</span> at the Shaw Conference Centre. TFC employs',
        timestamp: "2021-05-05T04:21:29Z",
      },
    ];
  }
  getCastListItem() {
    return {
      name: "Jack Nicholson",
      images: [
        {
          small: "https://image.tmdb.org/t/p/w45/6h12pZsgj3WWjMtykUgfLkLEBWz.jpg",
        },
        {
          small: "https://image.tmdb.org/t/p/w45/gNMokbwBSrBEMiv3qDBomloe7jD.jpg",
        },
      ],

      role: {
        character: "President James Dale / Art Land",
      },
    };
  }
}

export default TestResources;
